### PR TITLE
RFE: specfile and adding project page in git

### PR DESCRIPTION
**Pull request by truatpasteurdotfr**
Would you consider adding a copy of your project page in git?

I am not sure if you agree to provide a spec file for people to build packages out of the releases versions? In particular you allow it
```
LICENSE.txt:
...
You may NOT publically redistribute it, either in its original form, or
modified, without explicit consent by the author.
```

### CODE REVIEW

**Comment by ppbrown** [comment]
Hello, and thank you for your interest in zrep.
You seem to be asking for two things. generally it is best to either open separate issues for that, or use regular email.

I'm not sure what you mean by "adding a copy of your project page in git". So you would need to explain that separately, and help me understand what you are trying to accomplish there.

As far as the spec file goes.. what you wrote seems pretty reasonable.
However, in order to avoid any potential copyright issues, I do not accept merges.
Seeing as how it is a completely separate file though, I think I would be legally clear to include it if you agree to assign copyright of that file to me.
Do you agree to do so?

Also, as a technical detail.. i notice that the version of zrep is hardcoded into the spec file.
I have enough files to edit every time I do a release :-}
 isnt there some way for the build to automatically pull out the release number?

**Comment by truatpasteurdotfr** [comment]
- ok for transferring the copyright to you for the spec file
- you can generate the versionned spec file from a template, is that what you want?

**Comment by ppbrown** [comment]
yeah, I guess I'll adapt what you had, to be "zrep.spec.tmpl", and then add a "make zrep.spec" target ?

**Comment by ppbrown** [comment]
Hello,

I finally got around to makeing a spec file. 
please check latest commits and see if it works for you.

**Comment by ppbrown** [comment]
I am going to presume due to lack of feedback that it does, and closing this.

**Pull request closed without merging**
