### PR TITLE
fixed overly aggressive use of -s local in zrep_takeover

### PR DESCRIPTION
**Pull request by onlime**
Two more aggressive lines where the `received` property on the remote host did not get respected. Thanks for fixing!

### CODE REVIEW

**Comment by ppbrown** [comment]
thank you for identifying this bug speedily.
it seems like more places needed to be adjusted.
I've updated git appropriately. Please let me know if it works better for you.

**Comment by onlime** [comment]
thanks @ppbrown for the quickfix and your great work on zrep! Please also accept 44ae5d54ef64dd3f52a9cafa07e4f7e3d82d68a4 as this should fix the remaining issues with different output for `-s local` vs. all sources on non-existent properties. Or, if possible, find a less error prone solution, e.g. by a regex comparison "-|".

**Comment by ppbrown** [comment]
Doh... thanks again.
I hate inconsistant programs (zfs get vs get -s local)

**Comment by onlime** [comment]
thanks for pushing that. My latest 4 commits have nothing to do with this PR, so I am closing it.

**Pull request closed without merging**
