### PR TITLE
fixes stderr messages so that they no longer truncate log files

### PR DESCRIPTION
**Pull request by fmattheus**

### CODE REVIEW

**Comment by ppbrown** [comment]
hi Frank,
thanks for taking the time to put together a patch.
Could I get more details please?

What OS are you using, and how are you using zrep, that is causing problems?

FYI, I did some tests of my own using /dev/fd/2 on solaris.

   $ ./tester 2>/tmp/log.errs

creates a new logfile for each run of the program. However,

  $ ./tester 2>> /tmp/log.errs

preserves the existing log file.

I would imagine that some people WANT a fresh logfile for each run. So your
patch may not be good for all users.

**Comment by fmattheus** [comment]
first of all thanks so much for your great script, and for getting back to me about my fix.
I'm running on bash in linux and the following is happening.

I've created a very simple test case where you can see my issue.  Basically I want to have a single log file where I can see everything including errors.  You can also see that people who want a fresh logfile each time still get that.
test - Your original syntax
test2 - with an append

```
$ cat test
#!/bin/ksh -p
print everything fine
print here comes an error >/dev/fd/2
$ cat test2
#!/bin/ksh -p
print everything fine
print here comes an error >>/dev/fd/2
$ ./test > /tmp/log 2>&1
$ cat /tmp/log
here comes an error
$ ./test >> /tmp/log 2>&1
$ cat /tmp/log
here comes an error
$ ./test2 > /tmp/log 2>&1
$ cat /tmp/log
everything fine
here comes an error
$ ./test2 >> /tmp/log 2>&1
$ cat /tmp/log
everything fine
here comes an error
everything fine
here comes an error
$ ./test2 > /tmp/log 2>&1
$ ./test2 > /tmp/log 2>&1
$ cat /tmp/log
everything fine
here comes an error
$ ./test2 > /tmp/log 2>/tmp/log.err
$ ./test2 > /tmp/log 2>/tmp/log.err
$ cat /tmp/log.err
here comes an error
$ 
```

**Comment by ppbrown** [comment]
Hmm..
odd.

Test script on solaris, using bash as my login shell, and my own script:

hamachi$ ./tester > /tmp/log.errs 2>&1
hamachi$ ./tester >> /tmp/log.errs 2>&1
hamachi$ cat /tmp/log.errs
Initial program line
Friday, July 15, 2016 06:48:54 AM PDT this is line one
Friday, July 15, 2016 06:48:54 AM PDT this is line two
Closing program line
Initial program line
Friday, July 15, 2016 06:49:01 AM PDT this is line one
Friday, July 15, 2016 06:49:01 AM PDT this is line two
Closing program line

hamachi$ cat tester
#!/bin/ksh

echo Initial program line
echo "`date`" this is line one >/dev/fd/2
echo "`date`" this is line two >/dev/fd/2
echo Closing program line


But... when I run it on linux.. the output gets garbled. even on a SINGLE
run.
Even if I use tester 2>> /tmp/log.errs

linux stderr /dev/fd handling is broken :-/

I guess I'll come up with some workaround. It wont be exactly your patch
though.

**Comment by fmattheus** [comment]
Agree, very odd.  No worries.  Feel free to solve it as you wish, just wanted to contribute back :)

**Comment by ppbrown** [comment]
Apologies that i still cant think of a good *crossplatform* solution for this.
But I have at least made it easier for you to locally patch, by consolidating all the /dev/fd/2 stuff into one new routine, _errprint()

Thanks for the feedback, and if you come up with any more ideas, please let me know.
Thanks

**Pull request closed without merging**
