### PR TITLE
Fixed Z_HAS_O on SmartOS

### PR DESCRIPTION
**Pull request by foxycode**
On SmartOS (20170119T014200Z), there is no `recv -x` support, but there is `recv -o` support. Due to that, zvols can't be automatically initialised (I saw source code for initialize and don't know why).

FYI: This is how zfs help on SmartOS looks like:
```
missing command
usage: zfs command args ...
where 'command' is one of the following:

        create [-p] [-o property=value] ... <filesystem>
        create [-ps] [-b blocksize] [-o property=value] ... -V <size> <volume>
        destroy [-fnpRrv] <filesystem|volume>
        destroy [-dnpRrv] <filesystem|volume>@<snap>[%<snap>][,...]
        destroy <filesystem|volume>#<bookmark>

        snapshot [-r] [-o property=value] ... <filesystem|volume>@<snap> ...
        rollback [-rRf] <snapshot>
        clone [-p] [-o property=value] ... <snapshot> <filesystem|volume>
        promote <clone-filesystem>
        rename [-f] <filesystem|volume|snapshot> <filesystem|volume|snapshot>
        rename [-f] -p <filesystem|volume> <filesystem|volume>
        rename -r <snapshot> <snapshot>
        bookmark <snapshot> <bookmark>

        list [-Hp] [-r|-d max] [-o property[,...]] [-s property]...
            [-S property]... [-t type[,...]] [filesystem|volume|snapshot] ...

        set <property=value> ... <filesystem|volume|snapshot> ...
        get [-crHp] [-d max] [-o "all" | field[,...]]
            [-t type[,...]] [-s source[,...]]
            <"all" | property[,...]> [filesystem|volume|snapshot|bookmark] ...
        inherit [-rS] <property> <filesystem|volume|snapshot> ...
        upgrade [-v]
        upgrade [-r] [-V version] <-a | filesystem ...>
        userspace [-Hinp] [-o field[,...]] [-s field] ...
            [-S field] ... [-t type[,...]] <filesystem|snapshot>
        groupspace [-Hinp] [-o field[,...]] [-s field] ...
            [-S field] ... [-t type[,...]] <filesystem|snapshot>

        mount
        mount [-vO] [-o opts] <-a | filesystem>
        unmount [-f] <-a | filesystem|mountpoint>
        share <-a | filesystem>
        unshare <-a | filesystem|mountpoint>

        send [-DnPpRvLec] [-[iI] snapshot] <snapshot>
        send [-Le] [-i snapshot|bookmark] <filesystem|volume|snapshot>
        send [-nvPe] -t <receive_resume_token>
        receive [-vnsFu] <filesystem|volume|snapshot>
        receive [-vnsFu] [-o origin=<snapshot>] [-d | -e] <filesystem>
        receive -A <filesystem|volume>

        allow <filesystem|volume>
        allow [-ldug] <"everyone"|user|group>[,...] <perm|@setname>[,...]
            <filesystem|volume>
        allow [-ld] -e <perm|@setname>[,...] <filesystem|volume>
        allow -c <perm|@setname>[,...] <filesystem|volume>
        allow -s @setname <perm|@setname>[,...] <filesystem|volume>

        unallow [-rldug] <"everyone"|user|group>[,...]
            [<perm|@setname>[,...]] <filesystem|volume>
        unallow [-rld] -e [<perm|@setname>[,...]] <filesystem|volume>
        unallow [-r] -c [<perm|@setname>[,...]] <filesystem|volume>
        unallow [-r] -s @setname [<perm|@setname>[,...]] <filesystem|volume>

        hold [-r] <tag> <snapshot> ...
        holds [-r] <snapshot> ...
        release [-r] <tag> <snapshot> ...
        diff [-FHt] <snapshot> [snapshot|filesystem]

Each dataset is of the form: pool/[dataset/]*dataset[@name]

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
```

### CODE REVIEW

**Comment by ppbrown** [comment]
well, "awesome".

SmartOS.. has updated zfs.. in a way that is INCOMPATIBLE WITH THE STANDARD ZFS.
You should file a bug with them.

STANDARD ZFS, has this:
 receive [-vnFu] [[-o property=value] 


notice how the -o option has a completely different expected argument :(

So, as I said: please file a bug with them.

**Comment by foxycode** [comment]
@ppbrown I see, they implemented only one option, not all of them. My mistake.

But can you please tell me why is zvol initialisation forbidden? You are using only `-o readonly=yes` option when initialising and that could be set after transfer, if `-o` option isn't supported. I can prepare pull if you want.

**Comment by ppbrown** [comment]
To answer your question about WHY it is like that:

It used to be that doing a zfs send/receive with the particular options that zrep wants to use, to a volume...
would CRASH THE OS (solaris)
So, I used that feature check, as a sneaky way to test (Is the ZFS version later than the crashy version?)

**Comment by foxycode** [comment]
@ppbrown So are you ok adding check if it is SmartOS and allow init for SmartOS when it doesn't crash?

**Comment by ppbrown** [comment]
Potentially. 
The thing is though, the test for it will be tricky.
Unless you can boot up the oldest version of SmartOS, and verify it doesnt crash, doing something like
(If SmartOS then okay...)
would be irresponsible.

Side note: FYI, I'm a bit wierd; i dont like pull requests. I like writing code myself :)
So its usually best to file a bug and discuss issues with me, rather than jumping into writing code yourself and submitting it.

**Comment by foxycode** [comment]
@ppbrown I am using SmartOS from 2012 and sending zvol was always ok.

It's strange you don't like PR's. I wanted to help you and I tried to abide your coding standard. But ok, I reather create issu next time. Still I need to fix the code immediately in my repo, I need to use it.

**Comment by ppbrown** [comment]
its not just "sending zvol", it's "sending to a zvol that has been set readonly", if I recall correctly.
Virtually noone does that, so I'm guessing you didnt do that at the time either ;-}

I wish that there was more of a unified ZFS version standard, where I could just check version number.
Unfortunately.. there isnt. 
To use a made-up example, "ZFS version 123" in Solaris may be feature-comparable to "ZFS version 47" in OpenBSD or some such.
The ZFS version number is local to the OS-specific codebase, as far as I've found :(

**Comment by foxycode** [comment]
@ppbrown Not sure about earlier version, but I works current version, I just tested it.

I'm don't liek incompatibility in zfs too, it's reason why I wasn't able to use generally available backup script I tried earlier. You was small and straighforward, so I wanted to give it a try and make few needed changes. Unfortunately I don't know original Solaris or FreeBSD, I am using just SmartOS with ZFS.

I understand you don't want to support one more system with different ZFS, but I can help with that if you let me.

**Comment by ppbrown** [comment]
FUNNY THING.
My comments about Z_HAS_O were inaccurate.
It  wasnt about recv -o at all. It was for create -o

So I fixed that.
and fixed detection.
So, funnily enough, zrep will probably now  work for volume initialization on SmartOS, without any specific reference to SmartOS or uname -s or any other such hacks.

**Comment by ppbrown** [comment]
oh wait. No, it was actually really supposed to be for recv after all. 
sigh... have to think of something else...

**Comment by ppbrown** [comment]
decided to change check about volumes to warning, instead of exit

**Comment by foxycode** [comment]
Great :)

**Pull request closed without merging**
